// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetTaskByUserID(ctx context.Context, userID int32) ([]Task, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
}

var _ Querier = (*Queries)(nil)
