// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	// Insert a new post
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	// Insert a new user
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Delete a post
	DeletePost(ctx context.Context, id int32) error
	// Get a post by ID
	GetPost(ctx context.Context, id int32) (Post, error)
	// Get a user by username
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// List all posts
	ListPosts(ctx context.Context) ([]Post, error)
	// Update a post
	UpdatePost(ctx context.Context, arg UpdatePostParams) error
}

var _ Querier = (*Queries)(nil)
