// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package models

import (
	"database/sql"
)

type Post struct {
	ID        int32         `json:"id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	AuthorID  sql.NullInt32 `json:"author_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID             int32        `json:"id"`
	Username       string       `json:"username"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}
