// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

type User struct {
	ID             int32  `json:"id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}
